export const CREATE_CHALLENGE_REQUEST = 'CREATE_CHALLENGE_REQUEST';
export const CREATE_CHALLENGE_SUCCESS = 'CREATE_CHALLENGE_SUCCESS';
export const CREATE_CHALLENGE_ERROR = 'CREATE_CHALLENGE_ERROR';

export const CHALLENGE_LIST_REQUEST = "CHALLENGE_LIST_REQUEST";
export const CHALLENGE_LIST_SUCCESS = "CHALLENGE_LIST_SUCCESS";
export const CHALLENGE_LIST_FAIL = "CHALLENGE_LIST_FAIL";

export const GET_CHALLENGE_REQUEST = 'GET_CHALLENGE_REQUEST';
export const GET_CHALLENGE_SUCCESS = 'GET_CHALLENGE_SUCCESS';
export const GET_CHALLENGE_FAILURE = 'GET_CHALLENGE_FAILURE';

export const UPVOTE_CHALLENGE_REQUEST = 'UPVOTE_CHALLENGE_REQUEST';
export const UPVOTE_CHALLENGE_SUCCESS = 'UPVOTE_CHALLENGE_SUCCESS';
export const UPVOTE_CHALLENGE_FAIL = 'UPVOTE_CHALLENGE_FAIL';

export const QUIT_CHALLENGE_REQUEST = 'QUIT_CHALLENGE_REQUEST';
export const QUIT_CHALLENGE_SUCCESS = 'QUIT_CHALLENGE_SUCCESS';
export const QUIT_CHALLENGE_FAIL = 'QUIT_CHALLENGE_FAIL';

export const JOIN_CHALLENGE_REQUEST = 'JOIN_CHALLENGE_REQUEST';
export const JOIN_CHALLENGE_SUCCESS = 'JOIN_CHALLENGE_SUCCESS';
export const JOIN_CHALLENGE_FAIL = 'JOIN_CHALLENGE_FAIL';


export const CHECKIN_CHALLENGE_REQUEST = 'CHECKIN_CHALLENGE_REQUEST';
export const CHECKIN_CHALLENGE_SUCCESS = 'CHECKIN_CHALLENGE_SUCCESS';
export const CHECKIN_CHALLENGE_FAIL = 'CHECKIN_CHALLENGE_FAIL';

export const GET_CHECKED_IN_MESSAGES_REQUEST = "GET_CHECKED_IN_MESSAGES_REQUEST";
export const GET_CHECKED_IN_MESSAGES_SUCCESS = "GET_CHECKED_IN_MESSAGES_SUCCESS";
export const GET_CHECKED_IN_MESSAGES_FAIL = "GET_CHECKED_IN_MESSAGES_FAIL";

export const CHECK_STREAK_REQUEST = 'CHECK_STREAK_REQUEST';
export const CHECK_STREAK_SUCCESS = 'CHECK_STREAK_SUCCESS';
export const CHECK_STREAK_FAIL = 'CHECK_STREAK_FAIL';

export const COMPLETE_CHALLENGE_REQUEST = 'COMPLETE_CHALLENGE_REQUEST';
export const COMPLETE_CHALLENGE_SUCCESS = 'COMPLETE_CHALLENGE_SUCCESS';
export const COMPLETE_CHALLENGE_FAILURE = 'COMPLETE_CHALLENGE_FAILURE';


// challenges that user has interacted with
export const FETCH_CHALLENGES_REQUEST = 'FETCH_CHALLENGES_REQUEST';
export const FETCH_CHALLENGES_SUCCESS = 'FETCH_CHALLENGES_SUCCESS';
export const FETCH_CHALLENGES_FAIL = 'FETCH_CHALLENGES_FAIL';


export const CLEAR_MSG = "CLEAR_MSG";


