export const COMMENT_CREATE_REQUEST = "COMMENT_CREATE_REQUEST";
export const COMMENT_CREATE_SUCCESS = "COMMENT_CREATE_SUCCESS";
export const COMMENT_CREATE_FAIL = "COMMENT_CREATE_FAIL";


export const COMMENT_ALL_REQUEST = "COMMENT_ALL_REQUEST";
export const COMMENT_ALL_SUCCESS = "COMMENT_ALL_SUCCESS";
export const COMMENT_ALL_FAIL = "COMMENT_ALL_FAIL";