export const FETCH_CONVERSATION_REQUEST = 'FETCH_CONVERSATION_REQUEST';
export const FETCH_CONVERSATION_SUCCESS = 'FETCH_CONVERSATION_SUCCESS';
export const FETCH_CONVERSATION_FAILURE = 'FETCH_CONVERSATION_FAILURE';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const FETCH_CONVERSATION_LIST_REQUEST = 'FETCH_CONVERSATION_LIST_REQUEST';
export const FETCH_CONVERSATION_LIST_SUCCESS = 'FETCH_CONVERSATION_LIST_SUCCESS';
export const FETCH_CONVERSATION_LIST_FAILURE = 'FETCH_CONVERSATION_FAILURE';
