// postConstants.js
export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';

export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAIL = 'POST_DELETE_FAIL';

export const POST_LIKE_REQUEST = 'POST_LIKE_REQUEST';
export const POST_LIKE_SUCCESS = 'POST_LIKE_SUCCESS';
export const POST_LIKE_FAIL = 'POST_LIKE_FAIL';

export const POST_GET_ALL_REQUEST = 'POST_GET_ALL_REQUEST';
export const POST_GET_ALL_SUCCESS = 'POST_GET_ALL_SUCCESS';
export const POST_GET_ALL_FAIL = 'POST_GET_ALL_FAIL';

export const POST_GET_ALL_LIKES_REQUEST = 'POST_GET_ALL_LIKES_REQUEST';
export const POST_GET_ALL_LIKES_SUCCESS = 'POST_GET_ALL_LIKES_SUCCESS';
export const POST_GET_ALL_LIKES_FAIL = 'POST_GET_ALL_LIKES_FAIL';

export const POST_GET_SINGLE_REQUEST = 'POST_GET_SINGLE_REQUEST';
export const POST_GET_SINGLE_SUCCESS = 'POST_GET_SINGLE_SUCCESS';
export const POST_GET_SINGLE_FAIL = 'POST_GET_SINGLE_FAIL';

export const POST_GET_FOLLOWED_REQUEST = 'POST_GET_FOLLOWED_REQUEST';
export const POST_GET_FOLLOWED_SUCCESS = 'POST_GET_FOLLOWED_SUCCESS';
export const POST_GET_FOLLOWED_FAIL = 'POST_GET_FOLLOWED_FAIL';

export const POST_GET_MY_POSTS_REQUEST = 'POST_GET_MY_POSTS_REQUEST';
export const POST_GET_MY_POSTS_SUCCESS = 'POST_GET_MY_POSTS_SUCCESS';
export const POST_GET_MY_POSTS_FAIL = 'POST_GET_MY_POSTS_FAIL';